apiVersion: v1
kind: Service
metadata:
  name: shopee-scraper-api
  labels:
    app: shopee-scraper-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: shopee-scraper-api
